// =========================================================================
// GENERATED by n8n/build-score-node.js - DO NOT EDIT HERE.
// Sources: paymentsinfo.js, scorer.js (4 helpers), scorer-month.js.
// Edit those, run `node n8n/build-score-node.js`, then `node test-node-parity.js`.
// =========================================================================

// --- from scorer.js: the four helpers scorer-month.js imports ------------
function parseCardDate(s) {
  const m = String(s || '').trim().match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})$/);
  if (!m) return null;
  return Date.UTC(Number(m[3]), Number(m[1]) - 1, Number(m[2]));
}

function bucketOf(nationality, liveOut) {
  const v = String(nationality || '').trim().toLowerCase();
  if (v === '') return null; // empty string, not null, on maid-less contracts
  if (v === 'filipina') return 'Filipina';
  if (v === 'ethiopian') return liveOut ? 'Other' : 'Ethiopian';
  return 'Other';
}

function priceAt(card, cohort, whenMs) {
  if (whenMs === null) return null;
  const list = card.filter((w) => w.cohort === cohort);
  if (!list.length) return null;
  let latestStart = -Infinity;
  for (const w of list) {
    const s = parseCardDate(w.start);
    if (s !== null && s > latestStart) latestStart = s;
  }
  const hits = [];
  for (const w of list) {
    const s = parseCardDate(w.start);
    const e = parseCardDate(w.end);
    if (s === null) continue;
    const isFinal = s === latestStart;
    if (whenMs >= s && (isFinal || (e !== null && whenMs <= e))) hits.push(w);
  }
  // Windows within a cohort are non-overlapping by construction. More than one
  // match means the CARD IS CORRUPT - stop the run, never pick one.
  if (hits.length > 1) {
    const err = new Error('CARD CORRUPT: ' + hits.length + ' overlapping windows for ' + cohort);
    err.cardCorrupt = true;
    throw err;
  }
  return hits.length ? hits[0].price_inc_vat : null;
}

function parseDiscount(text) {
  const raw = String(text === null || text === undefined ? '' : text).trim();
  if (raw === '') return { monthly: 0, present: false };
  const amt = raw.match(/([\d,]+(?:\.\d+)?)/);
  if (!amt) return { monthly: 0, present: false };
  const total = Number(amt[1].replace(/,/g, ''));
  if (!isFinite(total) || total === 0) return { monthly: 0, present: false }; // "Amount: 0" is a real zero
  const months = raw.match(/over\s+(\d+)\s+month/i);
  const n = months ? Number(months[1]) : 1;
  return { monthly: total / (n > 0 ? n : 1), present: true };
}

// --- from paymentsinfo.js -----------------------------------------------
// ---------------------------------------------------------------------------
// paymentPlan.paymentsInfo parser.
//
// ERP publishes a contract's payment schedule as human-readable strings:
//
//   'Service Fees: 4490 + 225 VAT, on Nov 01 2026 (Monthly)'
//   'Service Fees: 3990 + 200 VAT, on Sep 01 2026 (Monthly (for 2 months))'
//   'Service Fees: 2027 + 102 VAT, on Today (One Time Payment)'
//
// This is the ONLY place a plan's structure is visible. currentPayment.amountValue
// is whatever period happens to be current - a joining fee, an intro rate, or the
// steady-state monthly - and reading it produced nine false "under-priced"
// findings on 2026-08-18.
//
// Parsing prose is load-bearing, so anything that does not match the expected
// shape is returned as a PARSE FAILURE and routed to a human. A line is never
// silently skipped: a dropped entry could hide the very rate being audited.
// ---------------------------------------------------------------------------

const MONTHS = { jan: 0, feb: 1, mar: 2, apr: 3, may: 4, jun: 5, jul: 6, aug: 7, sep: 8, oct: 9, nov: 10, dec: 11 };

// 'Nov 01 2026' -> UTC ms. Returns null for anything else, including 'Today',
// which the caller resolves against the contract's start date.
function parseEntryDate(s, contractStartMs) {
  const raw = String(s === undefined || s === null ? '' : s).trim();
  if (raw === '') return null;
  if (/^today$/i.test(raw)) return contractStartMs === undefined ? null : contractStartMs;
  const m = raw.match(/^([A-Za-z]{3})[a-z]*\s+(\d{1,2})\s+(\d{4})$/);
  if (!m) return null;
  const mon = MONTHS[m[1].toLowerCase()];
  if (mon === undefined) return null;
  return Date.UTC(Number(m[3]), mon, Number(m[2]));
}

function num(s) {
  const v = Number(String(s).replace(/,/g, ''));
  return isFinite(v) ? v : null;
}

// One line -> a structured entry, or {parse_failed: true} carrying the raw text.
function parseEntry(line, contractStartMs) {
  const raw = String(line === undefined || line === null ? '' : line).trim();
  if (raw === '') return { parse_failed: true, raw: raw, why: 'empty line' };

  // '<label>: <fee> + <vat> VAT, on <date> (<frequency>)'
  const m = raw.match(/^(.*?):\s*([\d,]+(?:\.\d+)?)\s*\+\s*([\d,]+(?:\.\d+)?)\s*VAT\s*,\s*on\s+(.+?)\s*\((.+)\)\s*$/i);
  if (!m) return { parse_failed: true, raw: raw, why: 'does not match the expected shape' };

  const fee = num(m[2]);
  const vat = num(m[3]);
  if (fee === null || vat === null) return { parse_failed: true, raw: raw, why: 'fee or VAT is not a number' };

  const effective = parseEntryDate(m[4], contractStartMs);
  if (effective === null) return { parse_failed: true, raw: raw, why: 'unreadable effective date: ' + m[4] };

  const freqText = m[5].trim();
  // The card is denominated in "minimum monthly payment + VAT", so the amount
  // that compares like-for-like is fee + VAT, not the fee alone.
  const amount = Math.round((fee + vat) * 100) / 100;

  let kind;
  if (/one\s*time/i.test(freqText)) kind = 'one_time';
  else if (/^monthly/i.test(freqText)) kind = 'monthly';
  else return { parse_failed: true, raw: raw, why: 'unrecognised frequency: ' + freqText };

  // 'Monthly (for 2 months)' bounds the entry to N months from its effective date.
  let durationMonths = null;
  const dur = freqText.match(/for\s+(\d+)\s+month/i);
  if (dur) durationMonths = Number(dur[1]);

  return {
    parse_failed: false,
    raw: raw,
    label: m[1].trim(),
    fee: fee,
    vat: vat,
    amount: amount,
    effective_ms: effective,
    kind: kind,
    duration_months: durationMonths,
  };
}

function ym(ms) {
  const d = new Date(ms);
  return d.getUTCFullYear() * 12 + d.getUTCMonth();
}

// Parses every line and resolves which MONTHLY entries apply to a given month.
//
// Coverage: an entry runs from its effective month until either its stated
// duration expires or the next monthly entry begins, whichever comes first.
// One-time entries are excluded entirely - a joining fee is not a rate.
function resolveMonthlyRate(paymentsInfo, auditMonthMs, contractStartMs) {
  const lines = Array.isArray(paymentsInfo) ? paymentsInfo : [];
  const parsed = lines.map(function (l) { return parseEntry(l, contractStartMs); });
  const failures = parsed.filter(function (e) { return e.parse_failed; });

  const monthly = parsed
    .filter(function (e) { return !e.parse_failed && e.kind === 'monthly'; })
    .sort(function (a, b) { return a.effective_ms - b.effective_ms; });

  const oneTime = parsed.filter(function (e) { return !e.parse_failed && e.kind === 'one_time'; });

  const target = ym(auditMonthMs);
  const applicable = [];
  for (let i = 0; i < monthly.length; i++) {
    const e = monthly[i];
    const from = ym(e.effective_ms);
    if (target < from) continue;

    let until = Infinity; // exclusive
    if (e.duration_months !== null) until = from + e.duration_months;
    if (monthly[i + 1]) {
      const nextFrom = ym(monthly[i + 1].effective_ms);
      // Truncate only when the next entry genuinely STARTS LATER. Two monthly
      // entries effective in the same month do not supersede one another - they
      // overlap, and both stay applicable so the caller routes to a human
      // instead of silently letting the later line win.
      if (nextFrom > from && nextFrom < until) until = nextFrom;
    }
    if (target < until) applicable.push(e);
  }

  return {
    parsed: parsed,
    parse_failures: failures,
    monthly_entries: monthly,
    one_time_entries: oneTime,
    applicable: applicable,
  };
}

// --- from scorer-month.js -----------------------------------------------
// ---------------------------------------------------------------------------
// MONTH-SCOPED SCORER
//
// Asks "was this contract priced correctly during month M?" instead of
// "is it priced correctly right now?". Design: design-month-scoped-audit.md.
//
// Two things this fixes, both of which produced false findings on 2026-08-18:
//   - the rate no longer comes from currentPayment.amountValue (which is
//     whatever period is current - often a one-time joining fee). It comes from
//     the paymentsInfo entry covering M. See rate-field-is-wrong.md.
//   - partial months are never audited, so pro-rating never needs computing.
//
// OUT OF SCOPE IS A THIRD OUTCOME. It is not a pending and not a finding, and
// it must never enter the denominator green/red/pending are measured against.
// ---------------------------------------------------------------------------


const TOLERANCE = 3.0; // AED absolute - a VAT rounding artefact, never a percentage

function parseIso(s) {
  const m = String(s || '').trim().match(/^(\d{4})-(\d{2})-(\d{2})/);
  if (!m) return null;
  return Date.UTC(Number(m[1]), Number(m[2]) - 1, Number(m[3]));
}

// 'YYYY-MM' -> {first, last} in UTC ms, inclusive.
function monthBounds(auditMonth) {
  const m = String(auditMonth || '').trim().match(/^(\d{4})-(\d{2})$/);
  if (!m) return null;
  const y = Number(m[1]);
  const mo = Number(m[2]) - 1;
  if (mo < 0 || mo > 11) return null;
  return { first: Date.UTC(y, mo, 1), last: Date.UTC(y, mo + 1, 0), year: y, month: mo };
}

// The current month is NEVER a valid default: on the 18th you cannot say whether
// this month was billed correctly, because it has not finished.
function lastCompletedMonth(nowMs) {
  const d = new Date(nowMs === undefined ? Date.now() : nowMs);
  let y = d.getUTCFullYear();
  let mo = d.getUTCMonth() - 1;
  if (mo < 0) { mo = 11; y -= 1; }
  return y + '-' + String(mo + 1).padStart(2, '0');
}

function cohortKey(bucket, liveOut) {
  return (liveOut ? 'liveout' : 'livein') + ':' + bucket;
}

// The living axis in force at instant T, reconstructed from the change log.
// A log entry records a change ON its date from oldValue to newValue, so the
// value at T is the newValue of the latest entry at or before T - and, before
// any entry exists, the oldValue of the earliest one. With no logs the current
// value has always been the value.
function liveOutAt(currentLiveOut, logs, tMs) {
  const list = (Array.isArray(logs) ? logs : [])
    .map(function (l) { return { ms: parseIso(l.date), oldValue: l.oldValue, newValue: l.newValue }; })
    .filter(function (l) { return l.ms !== null; })
    .sort(function (a, b) { return a.ms - b.ms; });
  if (!list.length) return currentLiveOut;
  if (tMs < list[0].ms) return String(list[0].oldValue).toUpperCase() === 'OUT';
  let v = null;
  for (const l of list) { if (l.ms <= tMs) v = l.newValue; }
  return String(v).toUpperCase() === 'OUT';
}

// Did this cohort's card price change part-way through M? A window that STARTS
// after the first of the month but on or before the last means the month had two
// prices. Flag it and hand it to a human - do not average, do not pick.
function cardChangedMidMonth(card, cohort, bounds) {
  return card.some(function (w) {
    if (w.cohort !== cohort) return false;
    const s = parseCardDate(w.start);
    return s !== null && s > bounds.first && s <= bounds.last;
  });
}

// Prices published on or before the first of M. A price that only came into
// existence AFTER the audit month cannot grandfather a contract during it.
function historicPricesUpTo(card, cohort, tMs) {
  return card
    .filter(function (w) {
      if (w.cohort !== cohort) return false;
      const s = parseCardDate(w.start);
      return s !== null && s <= tMs;
    })
    .map(function (w) { return w.price_inc_vat; });
}

function outOfScope(out, reason, detail) {
  out.scope = 'out_of_scope';
  out.scope_reason = reason;
  out.state = null;
  out.verdict = null;
  out.reason_code = null;
  out.needs_human = false;
  if (detail) out.scope_detail = detail;
  return out;
}

// contract fields consumed:
//   contract_id, maid_nationality, live_out, contract_start_date,
//   date_of_termination, scheduled_date_of_termination,
//   payments_info (array of ERP strings), live_in_out_logs,
//   additional_discount, credit_note_discount,
//   payment_term_nationality, payment_term_nationality_surface
function scoreMonth(c, card, opts) {
  const auditMonth = (opts && opts.audit_month) || lastCompletedMonth(opts && opts.nowMs);
  const bounds = monthBounds(auditMonth);
  if (!bounds) throw new Error('audit_month must be YYYY-MM, got: ' + auditMonth);

  const out = {
    contract_id: c.contract_id,
    audit_month: auditMonth,
    scope: 'in_scope',
    scope_reason: null,
    tests: {},
    reason_code: null,
    state: null,
    verdict: null,
    needs_human: false,
    gap_aed: null,
    actual_rate: null,
    card_price: null,
    card_price_at_start: null,
    cohort: null,
    cohort_at_start: null,
    flags: [],
  };

  // --- SCOPE: active for the WHOLE month -----------------------------------
  const startMs = parseIso(c.contract_start_date);
  if (startMs === null) return outOfScope(out, 'no_start_date');
  if (startMs > bounds.first) {
    // Started mid-M. Not audited for M; it enters the population for M+1.
    // This is what removes the brand-new-contract problem - no pro-rating,
    // no inferred rate, no special gate.
    return outOfScope(out, 'started_after_month_start', c.contract_start_date);
  }
  const termCandidates = [c.date_of_termination, c.scheduled_date_of_termination]
    .map(parseIso)
    .filter(function (v) { return v !== null; });
  const termMs = termCandidates.length ? Math.min.apply(null, termCandidates) : null;
  if (termMs !== null && termMs < bounds.last) {
    return outOfScope(out, 'terminated_before_month_end', new Date(termMs).toISOString().slice(0, 10));
  }

  // --- RATE: from paymentsInfo, selected for M -----------------------------
  // An EMPTY plan is not the same as "entries exist, none covers M". The first
  // means the plan could not be read and is a pending; only the second is a
  // legitimate out-of-scope. Collapsing them would drop contracts out of the
  // denominator for a reason that is actually a data failure.
  if (!Array.isArray(c.payments_info) || c.payments_info.length === 0) {
    out.state = 'pending';
    out.verdict = "Can't tell";
    out.reason_code = 'no_payment_plan';
    out.needs_human = true;
    return out;
  }
  const rates = resolveMonthlyRate(c.payments_info, bounds.first, startMs);
  out.parse_failures = rates.parse_failures.length;

  if (rates.parse_failures.length) {
    // Never silently skip a line: the dropped entry could be the rate being
    // audited. And never fall back to currentPayment.
    out.state = 'pending';
    out.verdict = "Can't tell";
    out.reason_code = 'rate_unreadable';
    out.needs_human = true;
    out.unreadable_lines = rates.parse_failures.map(function (f) { return f.raw; });
    return out;
  }
  if (rates.applicable.length === 0) {
    return outOfScope(out, 'no_rate_for_month',
      rates.monthly_entries.length ? 'monthly entries exist but none covers ' + auditMonth
                                   : 'no monthly entry at all (one-time only)');
  }
  if (rates.applicable.length > 1) {
    out.state = 'pending';
    out.verdict = "Can't tell";
    out.reason_code = 'multiple_rates_in_month';
    out.needs_human = true;
    out.rate_entries = rates.applicable.map(function (e) { return e.raw; });
    return out;
  }
  const entry = rates.applicable[0];
  out.actual_rate = entry.amount;
  out.rate_entry = entry.raw;
  // An introductory rate below card IS flagged for the months it applies. That
  // is a policy call recorded on 2026-08-19: report what was true that month and
  // let a human clear an approved promotion through needs_human, exactly as the
  // living-switch class is cleared. The flag exists so the human sees WHY.
  if (entry.duration_months !== null) out.flags.push('bounded_rate_period');

  // --- COHORT, as of the audit month ---------------------------------------
  const liveOutInMonth = liveOutAt(c.live_out, c.live_in_out_logs, bounds.first);
  if (liveOutInMonth === null || liveOutInMonth === undefined || liveOutInMonth === '') {
    out.state = 'pending';
    out.verdict = 'Unpriceable';
    out.reason_code = 'no_living_axis';
    out.needs_human = true;
    return out; // never default to live-in, it is the cheaper cohort
  }
  const bucket = bucketOf(c.maid_nationality, liveOutInMonth);
  if (bucket === null) {
    out.state = 'pending';
    out.verdict = 'Unpriceable';
    out.reason_code = 'no_nationality';
    out.needs_human = true;
    return out; // never default to Other - the cheapest live-in bucket
  }
  out.cohort = cohortKey(bucket, liveOutInMonth);

  // A switch INSIDE M means the contract sat in two cohorts that month. Unlike
  // the run-date scorer, a switch that completed before M is not ambiguous here:
  // the axis in force during M is fully determined, so only an in-month switch
  // routes to a human.
  const switchedInMonth = (Array.isArray(c.live_in_out_logs) ? c.live_in_out_logs : []).some(function (l) {
    const d = parseIso(l.date);
    return d !== null && d >= bounds.first && d <= bounds.last;
  });
  if (switchedInMonth) {
    out.flags.push('living_switch_in_month');
    out.needs_human = true;
  }

  // --- CARD, as of the first of M ------------------------------------------
  if (cardChangedMidMonth(card, out.cohort, bounds)) {
    out.flags.push('card_changed_mid_month');
    out.state = 'pending';
    out.verdict = "Can't tell";
    out.reason_code = 'card_changed_mid_month';
    out.needs_human = true;
    return out; // two published prices that month - never average, never pick
  }
  const pMonth = priceAt(card, out.cohort, bounds.first); // throws on a corrupt card
  out.card_price = pMonth;

  const cohortAtStart = (function () {
    const lo = liveOutAt(c.live_out, c.live_in_out_logs, startMs);
    const b = bucketOf(c.maid_nationality, lo);
    return b ? cohortKey(b, lo) : null;
  })();
  const pStart = cohortAtStart ? priceAt(card, cohortAtStart, startMs) : null;
  out.cohort_at_start = cohortAtStart;
  out.card_price_at_start = pStart;

  if (pMonth === null && pStart === null) {
    out.state = 'pending';
    out.verdict = 'Unpriceable';
    out.reason_code = 'no_window_covers_month';
    out.needs_human = true;
    return out;
  }
  // The live-out card BEGINS 2024-07-15. A contract older than its cohort's
  // first window has no price-at-start; flag it rather than let a false test
  // result imply one.
  if (pStart === null) {
    out.flags.push('unpriceable_at_start');
    out.needs_human = true;
  }

  // --- discounts narrow the expectation BEFORE any gap test ----------------
  // additionalDiscount is ALREADY reflected in the contract's own payment plan,
  // so subtracting it here would double-credit and turn a real shortfall green.
  // Carried as verifier context only.
  if (parseDiscount(c.additional_discount).present) out.flags.push('additional_discount_context_only');
  if (parseDiscount(c.credit_note_discount).present) out.flags.push('credit_note_discount_context_only');
  if (c.plan_item_discount_unreadable) out.flags.push('plan_item_discount_unreadable');

  // --- the tests -----------------------------------------------------------
  const actual = out.actual_rate;
  const within = function (exp) { return exp !== null && Math.abs(actual - exp) <= TOLERANCE; };
  const history = historicPricesUpTo(card, out.cohort, bounds.first).concat(
    cohortAtStart && cohortAtStart !== out.cohort ? historicPricesUpTo(card, cohortAtStart, bounds.first) : []
  );

  out.tests.price_in_month = within(pMonth);
  out.tests.price_at_contract_start = within(pStart);
  out.tests.any_historic_price = history.some(function (p) { return Math.abs(actual - p) <= TOLERANCE; });
  // No definition exists on the spec pages, so it is scored NOT PASSED by
  // decision and declared, never quietly assumed false.
  out.tests.upgrading_nationality = false;
  out.unimplemented_tests = ['upgrading_nationality'];
  // pro_rated is RETIRED by month scoping: a partial month is out of scope, so
  // there is no pro-rated payment left to test for.
  out.retired_tests = ['pro_rated'];

  const anyPassed = out.tests.price_in_month || out.tests.price_at_contract_start || out.tests.any_historic_price;

  if (anyPassed) {
    out.state = 'green';
    out.verdict = out.tests.price_in_month ? 'Priced correctly' : 'Grandfathered';
    out.reason_code = out.tests.price_in_month ? 'matches_card_for_month' : 'matches_published_price';
    // needs_human is ONE-WAY. A passing test must not clear a contract a gate
    // already routed - that is exactly the false clearance the gates exist for.
    if (out.needs_human) {
      out.state = 'pending';
      out.verdict = "Can't tell";
      out.reason_code = 'cleared_on_a_test_but_gate_requires_review';
    }
    return out;
  }

  if (c.payment_term_nationality_surface === 'unavailable') {
    out.flags.push('cpt_surface_unavailable');
  } else if (
    c.payment_term_nationality &&
    String(c.payment_term_nationality).trim().toLowerCase() !== String(c.maid_nationality).trim().toLowerCase()
  ) {
    out.flags.push('payment_term_nationality_mismatch');
  }

  const expected = pMonth !== null ? pMonth : pStart;
  out.gap_aed = Math.round((expected - actual) * 100) / 100;
  out.needs_human = true; // a question for the verifier, never an established loss

  if (out.flags.indexOf('unpriceable_at_start') !== -1) {
    out.state = 'pending';
    out.verdict = 'Unpriceable';
    out.reason_code = 'no_published_price_at_start';
    return out;
  }

  out.state = 'red';
  out.verdict = 'Under-priced';
  out.reason_code = 'below_card_unexplained';
  return out;
}

// --- n8n glue -------------------------------------------------------------
// Everything above this line is inlined verbatim from the tested sources.
// Everything below maps the ERP payloads onto the scorer's contract shape and
// onto the Cases table's columns.

if (typeof $input === 'undefined') {
  // Required as a module by test-node-parity.js, which proves the SHIPPED body
  // still agrees with scorer-month.js on every harness case.
  module.exports = { scoreMonth, resolveMonthlyRate, parseEntry, monthBounds, lastCompletedMonth, liveOutAt };
} else {
  const baton = $("Receive Baton").first().json;
  const params = baton.params;
  const card = baton.price_card.windows;
  const runId = params.run_id;
  const auditMonth = params.audit_month;
  if (!auditMonth) {
    throw new Error("params.audit_month is missing. Stage 2 refuses to score without a named audit month - scoring 'now' is what produced the withdrawn 2026-08-18 findings.");
  }

  // ERP sends booleans as booleans on the dynamic API and as strings elsewhere.
  // An unrecognised value stays NULL and routes to a human; it is never guessed,
  // because live-in is the cheaper cohort and a wrong guess clears real gaps.
  const coerceBool = function (v) {
    if (v === true || v === false) return v;
    const s = String(v === null || v === undefined ? "" : v).trim().toLowerCase();
    if (s === "") return null;
    if (s === "true" || s === "out" || s === "1") return true;
    if (s === "false" || s === "in" || s === "0") return false;
    return null;
  };
  const pick = function (a, b) { return (a === null || a === undefined || a === "") ? b : a; };
  const str = function (v) { return (v === null || v === undefined) ? "" : String(v); };

  const out = [];
  for (const it of $input.all()) {
    const j = it.json;
    const row = j.row;
    const d = j.details || {};
    const plan = d.paymentPlan || {};

    const base = {
      run_id: runId,
      case_key: runId + ":" + row.contract_id,
      contract_id: str(row.contract_id),
      client_id: str(row.client_id),
      audit_month: auditMonth,
      contract_start_date: str(pick(row.start_inline, d.contractStartDate)),
      maid_nationality: str(j.nationality),
      live_out: "",
      scope: "in_scope",
      scope_reason: "",
      cohort_now: "",
      cohort_at_start: "",
      agreed_monthly_rate: 0,
      card_price_for_month: 0,
      card_price_at_start: 0,
      gap_aed: 0,
      rate_entry: "",
      state: "",
      verdict: "",
      reason_code: "",
      reason_text: "",
      test_price_in_month: false,
      test_price_at_start: false,
      test_any_historic_price: false,
      test_upgrading_nationality: false,
      test_pro_rated: false,
      unimplemented_tests: "upgrading_nationality",
      retired_tests: "pro_rated",
      flags: "",
      needs_human: false,
      living_switch: false,
      unpriceable_at_start: false,
      payment_term_nationality_mismatch: false,
      payment_term_surface_unavailable: true,
      plan_item_discount_unreadable: false,
      additional_discount_present: false,
      credit_note_discount_present: false,
      pil_blocked: false,
      price_card_checksum_ok: baton.price_card.checksum_ok === true,
      scored_at: new Date().toISOString(),
      nationality_source: str(j.nationality_source),
    };

    // The monthly rate lives in details.paymentPlan.paymentsInfo. If that call
    // failed there is no rate to read, so the contract is a pending - never
    // scored from a partial payload and never quietly dropped from the run.
    if (j.details_status !== 200) {
      out.push({ json: Object.assign({}, base, {
        state: "pending",
        verdict: "Can't tell",
        reason_code: "details_unreadable_" + j.details_status,
        reason_text: "contract details returned HTTP " + j.details_status + ", so paymentsInfo could not be read",
        flags: "details_unreadable",
        needs_human: true,
      }) });
      continue;
    }

    const c = {
      contract_id: row.contract_id,
      maid_nationality: str(j.nationality),
      live_out: coerceBool(pick(row.live_out_inline, d.liveOut)),
      contract_start_date: pick(row.start_inline, d.contractStartDate),
      date_of_termination: d.dateOfTermination || null,
      scheduled_date_of_termination: pick(row.scheduled_termination_inline, d.scheduledDateOfTermination) || null,
      payments_info: Array.isArray(plan.paymentsInfo) ? plan.paymentsInfo : [],
      additional_discount: str(plan.additionalDiscount),
      credit_note_discount: str(plan.creditNoteDiscount),
      live_in_out_logs: Array.isArray(j.logs)
        ? j.logs.map(function (l) { return { date: l.date || null, oldValue: l.oldValue || null, newValue: l.newValue || null }; })
        : [],
    };

    const r = scoreMonth(c, card, { audit_month: auditMonth });
    const flags = r.flags.slice();

    // The live-in/out log decides which cohort applied during the month. If that
    // call failed the cohort rests on the population's current value alone, so
    // the verdict is not safe to clear - needs_human is one-way.
    if (j.logs_status !== 200) {
      flags.push("logs_unreadable_" + j.logs_status);
      if (r.scope === "in_scope") {
        r.needs_human = true;
        if (r.state === "green") { r.state = "pending"; r.verdict = "Can't tell"; r.reason_code = "cleared_on_a_test_but_gate_requires_review"; }
      }
    }

    const t = r.tests || {};
    out.push({ json: Object.assign({}, base, {
      live_out: c.live_out === null ? "unknown" : String(c.live_out),
      scope: r.scope,
      scope_reason: str(r.scope_reason),
      cohort_now: str(r.cohort),
      cohort_at_start: str(r.cohort_at_start),
      agreed_monthly_rate: r.actual_rate === null || r.actual_rate === undefined ? 0 : r.actual_rate,
      card_price_for_month: r.card_price === null || r.card_price === undefined ? 0 : r.card_price,
      card_price_at_start: r.card_price_at_start === null || r.card_price_at_start === undefined ? 0 : r.card_price_at_start,
      gap_aed: r.gap_aed === null || r.gap_aed === undefined ? 0 : r.gap_aed,
      rate_entry: str(r.rate_entry),
      state: str(r.state),
      verdict: str(r.verdict),
      reason_code: str(r.scope === "out_of_scope" ? r.scope_reason : r.reason_code),
      reason_text: (r.scope === "out_of_scope"
        ? "out of scope for " + auditMonth + ": " + r.scope_reason + (r.scope_detail ? " (" + r.scope_detail + ")" : "")
        : str(r.reason_code)) + (flags.length ? " | flags: " + flags.join(",") : ""),
      test_price_in_month: t.price_in_month === true,
      test_price_at_start: t.price_at_contract_start === true,
      test_any_historic_price: t.any_historic_price === true,
      flags: flags.join(","),
      needs_human: r.needs_human === true,
      living_switch: flags.indexOf("living_switch_in_month") !== -1,
      unpriceable_at_start: flags.indexOf("unpriceable_at_start") !== -1,
      additional_discount_present: flags.indexOf("additional_discount_context_only") !== -1,
      credit_note_discount_present: flags.indexOf("credit_note_discount_context_only") !== -1,
    }) });
  }
  return out;
}
