import { workflow, node, trigger, ifElse, expr } from '@n8n/workflow-sdk';

const runTrigger = trigger({
  type: 'n8n-nodes-base.webhook',
  version: 2.1,
  config: {
    name: 'Run (webhook)',
    parameters: {
      httpMethod: 'POST',
      path: 'cc-price-by-cohort-stage1',
      responseMode: 'responseNode',
      options: {},
    },
  },
});

const validateInputs = node({
  type: 'n8n-nodes-base.code',
  version: 2,
  config: {
    name: 'Validate Inputs',
    parameters: {
      jsCode: [
        '// The ERP bearer is taken PER RUN from the payload. It is never stored in a',
        '// credential, never written to a Data Table, and never echoed into output -',
        '// it is the audit-trail attribution for every read this run makes.',
        'const raw = $input.first().json || {};',
        'const body = raw.body || raw;',
        'const auth = body.erp_auth || {};',
        'const errors = [];',
        '',
        'const bearer = String(auth.bearer || "").trim();',
        'const deviceId = String(auth.device_id || "").trim();',
        'if (!/^Bearer\\s+\\S+/.test(bearer)) errors.push("erp_auth.bearer missing or not a Bearer token");',
        'if (!/^\\d+$/.test(deviceId)) errors.push("erp_auth.device_id missing or not numeric");',
        '',
        '// The device id must belong to the same session as the bearer. A mismatched',
        '// pair authenticates inconsistently and, worse, usually means the token came',
        '// from someone else. Checked here rather than discovered mid-run.',
        'let tokenUser = null;',
        'if (errors.length === 0) {',
        '  try {',
        '    const seg = bearer.replace(/^Bearer\\s+/, "").split(".")[1];',
        '    const claims = JSON.parse(Buffer.from(seg, "base64").toString("utf8"));',
        '    tokenUser = claims.user || null;',
        '    if (claims.device && String(claims.device) !== deviceId) {',
        '      errors.push("erp_auth.device_id does not match the device claim inside the bearer");',
        '    }',
        '    if (claims.exp && Number(claims.exp) * 1000 < Date.now()) {',
        '      errors.push("bearer has already expired - ERP tokens last ~24h, get a fresh one");',
        '    }',
        '  } catch (e) {',
        '    errors.push("bearer is not a decodable JWT");',
        '  }',
        '}',
        '',
        'const p = body.params || {};',
        'const runId = String(p.run_id || ("run-" + new Date().toISOString().replace(/[^0-9]/g, "").slice(0, 14)));',
        'const smoke = p.smoke === true;',
        '',
        'return [{ json: {',
        '  ok: errors.length === 0,',
        '  errors: errors,',
        '  params: {',
        '    run_id: runId,',
        '    check_id: (smoke ? "SMOKE-" : "") + "manual-cc-price-by-cohort",',
        '    check_name: "CC Client Paying According to Price by Type / Nationality / Start Date",',
        '    smoke: smoke,',
        '    started_at: new Date().toISOString(),',
        '    // Population guard, build-handover s9 q1. Warn-only was requested but the',
        '    // Skeleton Contract mandates an abort floor, so the band version is built',
        '    // and is trivially switchable via the payload.',
        '    population: {',
        '      abort_below: Number(p.abort_below === undefined ? 4600 : p.abort_below),',
        '      warn_below: Number(p.warn_below === undefined ? 4900 : p.warn_below),',
        '      max_divergence_pct: Number(p.max_divergence_pct === undefined ? 1 : p.max_divergence_pct),',
        '      warn_only: p.warn_only === true,',
        '    },',
        '    erp_auth: {',
        '      bearer: bearer,',
        '      token_bare: bearer.replace(/^Bearer\\s+/, ""),',
        '      device_id: deviceId,',
        '      // Recorded so every finding can be traced to the identity that read it.',
        '      acting_user: tokenUser,',
        '    },',
        '  },',
        '} }];',
      ].join('\n'),
    },
  },
});

const inputsOk = ifElse({
  version: 2.2,
  config: {
    name: 'Inputs OK?',
    parameters: {
      conditions: {
        options: { caseSensitive: true, leftValue: '', typeValidation: 'strict' },
        conditions: [
          { leftValue: expr('{{ $json.ok }}'), operator: { type: 'boolean', operation: 'true', singleValue: true } },
        ],
        combinator: 'and',
      },
    },
  },
});

const respond400 = node({
  type: 'n8n-nodes-base.respondToWebhook',
  version: 1.1,
  config: {
    name: 'Respond 400',
    parameters: {
      respondWith: 'json',
      responseCode: 400,
      responseBody: expr('{{ JSON.stringify({ ok: false, errors: $json.errors }) }}'),
      options: {},
    },
  },
});

const respond200 = node({
  type: 'n8n-nodes-base.respondToWebhook',
  version: 1.1,
  config: {
    name: 'Respond 200 (accepted)',
    parameters: {
      respondWith: 'json',
      responseCode: 200,
      responseBody: expr('{{ JSON.stringify({ ok: true, run_id: $json.params.run_id, note: "accepted; run continues asynchronously" }) }}'),
      options: {},
    },
  },
});

const readCard = node({
  type: 'n8n-nodes-base.googleSheets',
  version: 4.7,
  config: {
    name: 'Read Price Card',
    parameters: {
      resource: 'sheet',
      operation: 'read',
      documentId: { __rl: true, mode: 'id', value: '1F0cKdaxm9Ct701N5dMpyUQW1-KiiiN8eZgb725GXolE', cachedResultName: 'Price trends' },
      sheetName: { __rl: true, mode: 'list', value: 826582475, cachedResultName: 'Sheet1' },
      options: {
        dataLocationOnSheet: { values: { rangeDefinition: 'detectAutomatically', readRowsUntil: 'lastRowInSheet' } },
        outputFormatting: { values: { date: 'FORMATTED_STRING', general: 'UNFORMATTED_VALUE' } },
        returnAllMatches: 'returnAllMatches',
      },
    },
    credentials: { googleSheetsOAuth2Api: { id: 'cNk10BYICAh91OZX', name: 'Malaz' } },
  },
});

const parseCard = node({
  type: 'n8n-nodes-base.code',
  version: 2,
  config: {
    name: 'Parse + Assert Card',
    parameters: {
      jsCode: [
        '// PRICE CARD PARSER + CHECKSUM. Lifted verbatim from the proven throwaway',
        '// reader (1kX3isU27HfmPMU0), with the checksum promoted to a hard stop.',
        '// Column F ("Minimum monthly payment + VAT") is the comparison figure.',
        '// Column E is ex-VAT; comparing on it drops old-price agreement to 98.72%.',
        '// Parse BY HEADER NAME - the live-out Filipina 2025-09-15 row exports with',
        '// extra unlabelled cells appended, which shift positional parsing.',
        'const rows = [];',
        'for (const i of $input.all()) { rows.push(i.json); }',
        '',
        'function norm(s) { return String(s === undefined || s === null ? "" : s).trim(); }',
        '',
        'function bucketNationality(n) {',
        '  const v = norm(n).toLowerCase();',
        '  if (v === "filipina") return "Filipina";',
        '  if (v === "ethiopian") return "Ethiopian";',
        '  if (v === "") return null;',
        '  return "Other";',
        '}',
        '',
        'function liveOutOf(contractType) {',
        '  const v = norm(contractType).toLowerCase();',
        '  if (v.indexOf("live-out") !== -1 || v.indexOf("live out") !== -1) return true;',
        '  if (v.indexOf("live-in") !== -1 || v.indexOf("live in") !== -1) return false;',
        '  return null;',
        '}',
        '',
        'const windows = [];',
        'const rejected = [];',
        'for (const r of rows) {',
        '  const keys = Object.keys(r);',
        '  const get = function (want) {',
        '    for (const k of keys) { if (norm(k).toLowerCase() === want) { return r[k]; } }',
        '    return undefined;',
        '  };',
        '  const liveOut = liveOutOf(get("contract type"));',
        '  const bucket = bucketNationality(get("nationality"));',
        '  const start = get("start date");',
        '  const price = Number(get("minimum monthly payment + vat"));',
        '  if (liveOut === null || bucket === null || !isFinite(price) || price <= 0 || !norm(start)) {',
        '    rejected.push({ contract_type: norm(get("contract type")), nationality: norm(get("nationality")), start: norm(start) });',
        '    continue;',
        '  }',
        '  windows.push({',
        '    cohort: (liveOut ? "liveout" : "livein") + ":" + bucket,',
        '    live_out: liveOut, bucket: bucket,',
        '    start: norm(start), end: norm(get("end date")),',
        '    price_inc_vat: price,',
        '  });',
        '}',
        '',
        'const byCohort = {};',
        'for (const w of windows) { if (!byCohort[w.cohort]) byCohort[w.cohort] = 0; byCohort[w.cohort]++; }',
        'const cohortCount = Object.keys(byCohort).length;',
        '',
        '// HARD STOP: exactly 49 windows across exactly 5 cohorts. If the file changed',
        '// shape the run stops rather than auditing everyone against a partial card.',
        '// A silently-changed reference file scores every contract wrongly with no error.',
        'const checksumOk = windows.length === 49 && cohortCount === 5;',
        'if (!checksumOk) {',
        '  throw new Error(',
        '    "PRICE CARD CHECKSUM FAILED: expected 49 windows across 5 cohorts, got " +',
        '    windows.length + " windows across " + cohortCount + " cohorts. Run stopped; " +',
        '    "no contract was scored. Rejected rows: " + rejected.length',
        '  );',
        '}',
        '',
        'const params = $("Validate Inputs").first().json.params;',
        'return [{ json: {',
        '  params: params,',
        '  price_card: {',
        '    windows: windows,',
        '    rows_read: rows.length,',
        '    windows_parsed: windows.length,',
        '    cohorts: cohortCount,',
        '    checksum_ok: true,',
        '    rejected_rows: rejected.length,',
        '  },',
        '} }];',
      ].join('\n'),
    },
  },
});

const getContracts = node({
  type: 'n8n-nodes-base.httpRequest',
  version: 4.2,
  config: {
    name: 'Get Active CC Contracts',
    onError: 'continueErrorOutput',
    parameters: {
      method: 'POST',
      url: 'https://erpbackendpro.maids.cc/clientmgmt/contract/search/page',
      sendQuery: true,
      queryParameters: {
        parameters: [
          { name: 'page', value: '0' },
          // size stays at 40: above that this route hits a known sub-list bug.
          { name: 'size', value: '40' },
          { name: 'sort' },
          { name: 'searchKey' },
          { name: 'unAssignedClients', value: 'false' },
          { name: 'vipClients', value: 'false' },
          { name: 'vVip', value: 'false' },
          { name: 'gccClients', value: 'false' },
        ],
      },
      sendHeaders: true,
      headerParameters: {
        parameters: [
          { name: 'pagecode', value: 'ClientList' },
          { name: 'accept', value: 'application/json, text/plain, */*' },
          { name: 'content-type', value: 'application/json' },
          { name: 'origin', value: 'https://erp.maids.cc' },
          { name: 'referer', value: 'https://erp.maids.cc/' },
          { name: 'authorization', value: expr("{{ $('Validate Inputs').first().json.params.erp_auth.bearer }}") },
          // The golden sends bearer only; the traps file mandates the cookie too.
          // Sending both is the safe superset until the probe settles which is right.
          { name: 'cookie', value: expr("{{ 'authTokenProduction=' + $('Validate Inputs').first().json.params.erp_auth.token_bare + '; deviceIdProduction=' + $('Validate Inputs').first().json.params.erp_auth.device_id }}") },
        ],
      },
      sendBody: true,
      specifyBody: 'json',
      // includeNullNationality is INVERTED on this route: false returns ~5,283
      // rows, true returns ~1,043. Do not "correct" it on the strength of its name.
      jsonBody: expr('{{ JSON.stringify({ contract: { status: "ACTIVE", contractProspectType: { code: "maids.cc_prospect" }, client: null, housemaid: { nationality: null }, contractType: null }, extraFilters: [], flowTypeCode: null, paymentMethod: null, bankIds: [], clientNationalityIds: [], includeNullNationality: false, emirate: null, clientsWithMultipleContracts: false }) }}'),
      options: {
        batching: { batch: { batchSize: -1, batchInterval: 0 } },
        response: { response: { responseFormat: 'json' } },
        pagination: {
          pagination: {
            parameters: { parameters: [{ name: 'page', value: expr('{{ $pageCount }}') }] },
            paginationCompleteWhen: 'other',
            completeExpression: expr('{{ Array.isArray($response.body?.clients?.content) && $response.body.clients.content.length === 0 }}'),
            limitPagesFetched: true,
            maxRequests: 200,
            requestInterval: 250,
          },
        },
        timeout: 90000,
      },
    },
  },
});

const populationGuard = node({
  type: 'n8n-nodes-base.code',
  version: 2,
  config: {
    name: 'Population Guard',
    parameters: {
      jsCode: [
        '// POPULATION COMPLETENESS (build-handover s9 q1).',
        '// A short pull produces a smaller, cleaner-looking report that is',
        '// indistinguishable from a genuinely clean month. That is the failure this',
        '// gate exists to catch, so it aborts rather than warns by default.',
        'const params = $("Parse + Assert Card").first().json.params;',
        'const card = $("Parse + Assert Card").first().json.price_card;',
        'const cfg = params.population;',
        '',
        'const rows = [];',
        'let reportedTotal = null;',
        'for (const item of $input.all()) {',
        '  const b = item.json || {};',
        '  const page = (b.clients && Array.isArray(b.clients.content)) ? b.clients.content : [];',
        '  for (const r of page) { rows.push(r); }',
        '  // `total` is available on this route - the handover\'s "no total, empty-page',
        '  // terminator only" applies to the dynamic-API pull, not to this one.',
        '  if (reportedTotal === null && b.total !== undefined && b.total !== null) reportedTotal = Number(b.total);',
        '}',
        '',
        '// De-duplicate on contract id. Aggregates on ERP endpoints have been measured',
        '// wrong by joins fanning rows out, so the de-duped count is the real one and',
        '// `total` is only the independent cross-check.',
        'const seen = {};',
        'const contracts = [];',
        'let dupes = 0;',
        'for (const r of rows) {',
        '  const id = String(r.contractId || r.id || r.contract_id || "");',
        '  if (!id) continue;',
        '  if (seen[id]) { dupes++; continue; }',
        '  seen[id] = true;',
        '  contracts.push(r);',
        '}',
        '',
        'const count = contracts.length;',
        'const independent = reportedTotal;',
        'const delta = independent === null ? null : count - independent;',
        'const deltaPct = (independent === null || independent === 0) ? null : Math.abs(delta) / independent * 100;',
        '',
        'const problems = [];',
        'if (count < cfg.abort_below) problems.push("population " + count + " is below the abort floor " + cfg.abort_below);',
        'if (deltaPct !== null && deltaPct > cfg.max_divergence_pct) {',
        '  problems.push("population diverges from the independent count by " + deltaPct.toFixed(2) + "% (limit " + cfg.max_divergence_pct + "%)");',
        '}',
        '',
        'const warn = count >= cfg.abort_below && count < cfg.warn_below;',
        'const complete = problems.length === 0 && !warn;',
        '',
        'if (problems.length && !cfg.warn_only) {',
        '  throw new Error("POPULATION GUARD FAILED: " + problems.join("; ") + ". Run stopped; no contract was scored.");',
        '}',
        '',
        'return [{ json: {',
        '  params: params,',
        '  price_card: card,',
        '  population: {',
        '    count: count,',
        '    independent_count: independent,',
        '    delta: delta,',
        '    delta_pct: deltaPct,',
        '    duplicates_dropped: dupes,',
        '    complete: complete,',
        '    guard: problems.length ? "failed-warn-only" : (warn ? "warn-band" : "ok"),',
        '    guard_notes: problems.join("; "),',
        '    source: "contract/search/page",',
        '  },',
        '  contracts: contracts,',
        '} }];',
      ].join('\n'),
    },
  },
});

const assembleBaton = node({
  type: 'n8n-nodes-base.code',
  version: 2,
  config: {
    name: 'Assemble Baton',
    parameters: {
      jsCode: [
        '// Slim baton for Stage 2. Only the fields the cohort key and the gates need',
        '// travel onward - per-contract payloads across ~5,000 contracts would blow',
        '// the 100 MB retained-data line in a single execution, which is the whole',
        '// reason this check is a 3-stage chain.',
        'const src = $input.first().json;',
        'const slim = [];',
        'for (const c of src.contracts) {',
        '  slim.push({',
        '    contract_id: String(c.contractId || c.id || c.contract_id || ""),',
        '    client_id: String(c.clientId || (c.client && c.client.id) || ""),',
        '    // Cohort inputs are NOT carried inline by this route - Stage 2 enriches',
        '    // them per contract. Recorded as null rather than guessed.',
        '    maid_nationality: c.maidNationality === undefined ? null : c.maidNationality,',
        '    live_out: c.maidLiveOut === undefined ? null : c.maidLiveOut,',
        '    contract_start_date: c.startDate === undefined ? null : c.startDate,',
        '  });',
        '}',
        'return [{ json: {',
        '  params: src.params,',
        '  price_card: src.price_card,',
        '  population: src.population,',
        '  contracts: slim,',
        '} }];',
      ].join('\n'),
    },
  },
});

export default workflow('cc-price-by-cohort-stage1', 'CC Price by Cohort · 1-Score')
  .add(runTrigger)
  .to(validateInputs)
  .to(inputsOk
    .onTrue(respond200.to(readCard).to(parseCard).to(getContracts).to(populationGuard).to(assembleBaton))
    .onFalse(respond400));
